@extends('layouts.compliance')

@section('content')

<div class="trow_ child-center">
<div id="our-temrs" class="trow_ mw-1000 cnt-left">
<br><br>
    <h1>ComplianceReward&#8480; Program Terms of Service</h1>
    <p>Last Updated on February 14, 2019</p>
    <p>Please read these Terms of Service ("Terms") carefully. These Terms are a binding electronic contract between you and Compliance Reward, LLC ("CR", "Company", "we", "us" or "our") governing the registration and use of our ComplianceReward&#8480; services as described below ("Service"). By registering for or using the Service via the ComplianceReward&#8480; mobile application ("Application") or the associated online website <a href="www.ComplianceReward.com">www.ComplianceReward.com</a>  ("Website") you agree to be bound by these Terms. These Terms affect your legal rights and obligations, so if you do not agree to these Terms, do not register or use the Service.</p>

    <p><strong>NO MEDICAL ADVICE:</strong> Neither the Website, the Application, nor the Services should be used for medical problems or conditions. If you have or suspect that you have a medical problem or condition, please contact a qualified health care professional immediately. If you are in the United States and are experiencing a medical emergency, please call 911 or call for emergency medical help on the nearest telephone.<p>
    <p><strong>ARBITRATION NOTICE:</strong> EXCEPT FOR CERTAIN TYPES OF DISPUTES DESCRIBED IN THE ARBITRATION CLAUSE BELOW, YOU AGREE THAT DISPUTES BETWEEN YOU AND CR WILL BE RESOLVED BY MANDATORY BINDING ARBITRATION AND YOU WAIVE ANY RIGHT TO PARTICIPATE IN A CLASS-ACTION LAWSUIT OR CLASS-WIDE ARBITRATION.</p>
    <h2>Privacy</h2>
    <p>Your privacy is important to us. The Compliance Reward Privacy Policy is incorporated into these Terms by reference. By accepting these Terms, you agree to the collection, use, and sharing of your information, including your content, through the Service in accordance with the Compliance Reward  Privacy Policy.</p>
    <h2>Modifications to these Terms</h2>
    <p>We may, at our sole discretion, revise these Terms from time to time. The most current version of these Terms will be made available to you on the Website and will be linked to from within the Application. We encourage you to periodically review these Terms. If we make material changes to these Terms, we will notify you on the Website or within the Application or both by posting a conspicuous notice on the Services or by otherwise sending you a notification prior to the effective date of the changes. By continuing to access or use the Services after those changes become effective, you agree to be bound by the revised Terms. If you do not agree to the revised Terms, you may terminate your account as set forth below.</p>

    <h2>ComplianceReward&#8480; Service</h2>
    <p>The Service is a prescription discount program that generates a ComplianceReward&#8480; card tied to your Account. If you do not have health insurance, you can use your ComplianceReward&#8480; card for any brand name or generic prescriptions you or a household member pays for out-of-pocket. If you have health insurance coverage, use your ComplianceReward&#8480; card for any prescriptions that are not covered by your insurance or for savings for your family members not covered by insurance.</p>
    <p><h2>DISCOUNT ONLY - NOT INSURANCE.</h2> The Service is NOT a health insurance policy and is not intended as a substitute for health insurance. The Service allows you to obtain discounts on prescription drugs purchased through participating providers. You are required to pay for all prescription drugs at the time of purchase. To obtain discounts, you will need to present your ComplianceReward&#8480; card before you pay for any prescription. The range of the discounts will vary depending on the prescription drug and the participating pharmacy. CR does not make payments to any pharmacy or health care provider through the Service.<p>
    <p>A listing of participating pharmacies is available at <a href="www.ComplianceReward.com">www.ComplianceReward.com</a>.</p>
    <p>The Service is administered by<br>
    Compliance Reward, LLC<br>
    3201 Fannin Lane;<br>
    Southlake, TX 76092<br>
    <a href="www.ComplianceReward.com">www.ComplianceReward.com</a>.</p>

    <p>You may cancel your Account or file a complaint regarding the Service at any time by contacting Customer Care at <a href="mailto:customercare@ComplianceReward.com">customercare@ComplianceReward.com</a> .</p>
    <h2>Online Health Initiative Survey</h2>
    <p>CR may offer the opportunity to participate in an Online Health Initiative Survey, which will request from you certain information on medical and other conditions. Your answers to an online Health Initiative Survey will allow us to send you educational information on certain medical conditions as well as information on additional savings opportunities related to the treatment of those medical conditions. THE ONLINE HEALTH INITIATIVE SURVEY SERVICE PROVIDED THROUGH THE APPLICATION IS DIFFERENT FROM THE DIAGNOSTIC SERVICES TYPICALLY PROVIDED BY A PHYSICIAN AND THE RESULTS SHOULD NOT BE CONSIDERED AS THE ADVICE OF A HEALTH CARE PROFESSIONAL. This service will not have the benefit of information that would be obtained by examining you in person and observing your physical condition. Therefore, the Online Health Initiative Survey results may not take into account particular facts or information that would affect a physician's opinion of your medical condition. In some cases, the facts may be critical to the opinion.</p>
    <p>BY DECIDING TO ANSWER ANY ONLINE HEALTH INITIATIVE SURVEY, YOU ACKNOWLEDGE AND AGREE THAT THE ONLINE HEALTH INITIATIVE SURVEY IS NOT INTENDED TO REPLACE A FULL MEDICAL EVALUATION OR A FACE-TO-FACE VISIT WITH A PHYSICIAN. FURTHER, YOU ACKNOWLEDGE AND AGREE TO SOLELY ASSUME THE RISK OF THESE LIMITATIONS AND FURTHER UNDERSTAND THAT NO WARRANTY OR GUARANTEE HAS BEEN MADE TO YOU CONCERNING ANY PARTICULAR RESULT OR CURE OF YOUR CONDITION.</p>
    <h2>General Conditions</h2>
    <ul><li>Use of the Services via the Application requires the download of the Application from the Apple iTunes App Store or the Google Play Store. Download of any Application is subject to the applicable End User License Agreement. You may also register for and use the Service through the Website.</li>
    <li>If you choose to create an account you will be required to provide us with your name, email address, date of birth and zip code to submit your registration and open your account ("Account"). Information that we collect during registration will be used as set forth in our Privacy Policy.</li>
    <li>You must be at least 13 years old to use the Service.</li>
    <li>CR prohibits the creation of and you agree that you will not create an Account for anyone other than yourself. You also represent that all information you provide to CR upon registration and at all other times will be true, accurate, current and complete and you agree to update your information as necessary to maintain its truth and accuracy.</li>
    <li>We reserve the right to refuse access to the Service to anyone for any reason at any time.</li>
    <li>We reserve the right to force forfeiture of any username for any reason.</li>
    <li>You agree that you are responsible for all data charges and/or SMS charges you incur through use of the Service.</li></ul>
    <h2>Modifications to Services</h2>
    <ul><li>We reserve the right to modify or terminate the Service or your access to the Service for any reason, at any time, and without liability to you.</li></ul>
    <h2>Termination of Your Account</h2>
    <ul><li>You can deactivate your Account within the settings of the Service or by requesting the deactivation of your account at <a href="mailto:customercare@ComplianceReward.com">customercare@ComplianceReward.com</a></li>
    <li>We may also terminate your access to the Service if we believe you have materially breached these terms or your use of the Services otherwise presents any legal or other risk to CR or any third party.</li>
    <li>If we terminate your access to the Service or if you request the deactivation of your account by emailing the address above, your data will no longer be accessible through your Account.</li>
    <li>Upon termination, all licenses and other rights granted to you in these Terms will immediately cease.</li>
    <li>There may be links embedded in the Service, or from images or content within the Service, to third party websites or features. We do not control, maintain or endorse any content or materials provided by any third party. If you choose to access such third-party websites or materials you do so at your own risk. We encourage you to visit the terms and policies applicable to such websites and materials.</li></ul>
    <h2>Using Your Account</h2>
    <p>The patient authorizes the use of a third-party application ComplianceReward.com  or a licensed white label product developed by Compliance Reward LLC and voluntarily provides patient name, shipping address, date of birth, insurance information, co-pay assistance cards and medications they seek transferred from another pharmacy.</p>
    <p>The patient grants explicit permission for CR to share elements of a prescription and health information with dispensing pharmacies and sponsors in order to safely coordinate the delivery and advisories and to receive compliance sponsorship. These elements include medication names, quantity refills, Prescriber name, reimbursement data, current refills, drug information and results of surveys or outreach performed by payer details.</p>
    <p>The patient permits CR to contact them in a secure and direct nature about information pertaining to recalls, shortages, proactive patient safety and proper use advisories, notification of refills or the expiration of a prescription, lower cost alternatives and to conduct surveys or confirmation as part of a compliant support program.</p>
    <p>The patient acknowledges enrollment in ComplianceReward&#8480; by CR  to establish a bank of "points" provided by CR and various sponsors, to retain a virtual wallet on their behalf to distribute payment to applicable service providers.</p>
    <p>For example, a dispensing pharmacy or medical marketplace partner may receive a distribution from the pointe balance in the form of cash where a sponsor allows. CR will keep an accounting of payments made on behalf of member in a year end statement.</p>
    <h2>Use of Your Account</h2>
    <ul><li>You acknowledge and agree that you do not have any ownership or other property interest in your Account. Your Account and all rights in your Account are owned by CR. However, subject to your compliance with these Terms, you are allowed to use your Account as set forth in these Terms.</li>
    <li>You are responsible for any activity that occurs through your Account. You are solely responsible for all transactions and activities undertaken by anyone utilizing your Account or your ComplianceReward&#8480; card, whether authorized or unauthorized. This includes any and all purchases, authorized or unauthorized, made from pharmacies.</li>
    <li>You must immediately notify CR of any suspected unauthorized transactions associated with your Account or your ComplianceReward&#8480; card or any other breach of security.</li>
    <li>You may not sell, transfer, license or assign your Account, username, or any Account rights to anyone.</li>
    <li>You are responsible for keeping your password secret and secure.</li>
    <li>You understand and agree that you use the Service at your own risk.</li>
    <li>BY ACCESSING OR USING THE SERVICE YOU REPRESENT AND WARRANT THAT YOUR ACTIVITIES ARE LAWFUL IN EVERY JURISDICTION WHERE YOU ACCESS OR USE THE SERVICE.</li></ul>
    <h2>Prohibited Activities</h2>
    <p>In addition to the other restrictions outlined in these Terms, you agree that you will not:</p>
    <ul><li>Use the Service for any purpose that is illegal, unauthorized, beyond the scope of its intended use, or engage in, encourage, promote, advocate or assist any third party in any activity that violates these Terms or is otherwise prohibited in these Terms or the terms of any third party that govern a particular Service;</li>
    <li>Interfere with or disrupt servers or networks used by CR to provide the Service or used by other users to access the Service, or violate any third party regulations, policies or procedures of such servers or networks or harass or interfere with another user's full use and enjoyment of the Service;</li>
    <li>Send any unsolicited or unauthorized advertising, spam, solicitations, or promotional materials to other users of the Service;</li>
    <li>Solicit or attempt to solicit personal information from other users of the Service;</li>
    <li>Intercept, examine, monitor or otherwise observe any proprietary communications protocol used by a device, a client or a server communicating with the Service, whether through the use of a network analyzer, packet sniffer or other device or software, unless expressly authorized by the company;</li>
    <li>Use any robot, bot, spider, crawler, scraper, or other automated means or interface not provided by us to access the Service or to extract data;</li>
    <li>Reverse engineer, decompile, disassemble, decipher or otherwise attempt to derive the source code for any underlying software or other intellectual property used to provide the Service or circumvent measures employed to prevent or limit access to any area, content, or source code of the Service;</li>
    <li>Use or attempt to use another userâ€™s account without authorization;</li>
    <li>Attempt to compromise any security measures or circumvent any content-filtering techniques we employ, or attempt to access areas or features of the Service that you are not authorized to access;</li>
    <li>Attempt to represent in any manner that you have a relationship of any kind with us or that we have endorsed you or any products or services without our express written consent to do so;</li>
    <li>Engage in or encourage, promote, advocate or assist any third party in any harassing, bullying, intimidating, predatory, or stalking activities;</li>
    <li>You may not post violent, nude, partially nude, discriminatory, unlawful, infringing, hateful, pornographic or sexually suggestive photos or other similar content via the Service;</li>
    <li>Impersonate any person or entity or otherwise misrepresent your affiliation with a person or entity;</li>
    <li>Make available any content that infringes the rights of any person or entity, including without limitation, any patent, trademark, trade secret, copyright, privacy, publicity or other proprietary or contractual rights;</li>
    <li>Reproduce, duplicate, copy, buy, sell, trade, resell or exploit for any commercial purpose any portion of the Service, including your Account, Company Materials (as defined below), or access to or use of the Service or Company Materials without our prior written consent; and</li>
    <li>Develop any third party applications that interact with other users of the Service or the Service without prior written consent from CR.</li></ul>
    <p>You further agree to abide by any third party terms when posting reviews of CR, the Service, the Website or the Application, including the Apple iTunes App Store Terms of Service.</p>
    <h2>Company Materials</h2>
    <p>Compliance Reward, LLC 2019</p>

    <p><strong>All rights reserved.</strong></p>
    <p>The ComplianceReward&#8480; logo, and other CR trademarks, service marks, graphics and logos used in connection with the Service are trademarks or registered trademarks of CR or its affiliates (collectively "CR Marks"). Third party trademarks, service marks, graphics and logos used in connection with the Application are the trademarks of their respective owners (collectively "Third-Party Marks"). The CR Marks and Third-Party Marks may not be copied, imitated or used, in whole or in part, without the prior written permission of CR or the applicable trademark holder.</p>
    <p>Unless otherwise stated, all materials contained on or within the Service, the Application or the Website that are provided by CR, including, but not limited to, text, graphics, images, code, illustrations, designs, icons, photographs, and written and other materials (collectively, "Company Materials"), as well as their selection and arrangement, are protected by copyright, trademark, trade dress, patent, and/or other intellectual property laws.</p>
    <p>Subject to your compliance with these Terms, CR grants you a limited, nonexclusive, non-sub-licensable license to access and use the Service and Company Materials solely as made available in the Application or Website. This license is revocable at any time as further contemplated by these Terms. You may not:</p>
    <ul><li>Distribute, publicly perform or publicly display any Company Materials;</li>
    <li>Modify or make any derivative uses of the Service or Company Materials, or any portion thereof;</li>
    <li>Download any portion of the Service, Company Materials, or any information contained therein, except as expressly permitted by the Service;</li>
    <li>Copy, reproduce, republish, frame, download, transmit, modify, display, reverse engineer, sell, or participate in any sale of, rent, lease, loan, assign, distribute, license, sublicense, or exploit in any way, in whole or in part, Company Materials, the Service, the Application, the Website or any related software, except as expressly stated in these Terms; or</li>
    <li>Otherwise use the Service or Company Materials other than for their intended purposes.</li></ul>
    <p>You may not use Company Materials in any manner except as necessary to use the Services as provided by CR. CR does not grant you any other right or license to use the Company Materials. Unauthorized use of Company Materials is a violation of these Terms, which may result in the termination of your Account, and may constitute a violation of applicable federal and state laws.</p>
    <h2>Feedback</h2>
    <p>You agree that submission of feedback, suggestions, ideas, or other information or materials regarding CR, the Application, the Website or any other component of the Service that you provide, whether by email or otherwise ("Feedback") is at your own risk and that Company has no obligations (including without limitation obligations of confidentiality) with respect to such Feedback. You represent and warrant that you have all rights necessary to submit the Feedback. You hereby grant to CR a fully paid, royalty-free, perpetual, irrevocable, worldwide, non-exclusive, and fully sub-licensable right and license to use, reproduce, perform, display, distribute, adapt, modify, re- format, create derivative works of, and otherwise commercially or non-commercially exploit in any manner, any and all Feedback, and to sub-license the foregoing rights, in connection with the operation and maintenance of the Service, the Application and the Website.</p>
    <h2>Disclaimer of Warranties</h2>
    <p>THE SERVICE, AND COMPANY MATERIALS, TOGETHER WITH THE APPLICATION AND THE WEBSITE, ARE PROVIDED "AS IS", "AS AVAILABLE" AND "WITH ALL FAULTS". TO THE FULLEST EXTENT PERMISSIBLE BY LAW, NEITHER CR NOR OUR MANAGING MEMBERS, SHAREHOLDERS, EMPLOYEES, MANAGERS, OFFICERS, AND AGENTS (COLLECTIVELY, THE "CR PARTIES") MAKE ANY REPRESENTATIONS OR WARRANTIES OR ENDORSEMENTS OF ANY KIND WHATSOEVER, EXPRESS OR IMPLIED, AS TO: (A) THE SERVICE; (B) THE COMPANY MATERIALS, INCLUDING THE APPLICATION AND WEBSITE; (C) CONTENT OR THIRD PARTY CONTENT; OR (D) SECURITY ASSOCIATED WITH THE TRANSMISSION OF INFORMATION TO CR OR VIA THE SERVICE. IN ADDITION, THE CR PARTIES HEREBY DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, TITLE, CUSTOM, TRADE, QUIET ENJOYMENT, SYSTEM INTEGRATION AND FREEDOM FROM COMPUTER VIRUS.</p>
    <p>THE CR PARTIES DO NOT REPRESENT OR WARRANT THAT THE SERVICE, WEBSITE OR APPLICATION WILL BE ERROR-FREE OR UNINTERRUPTED; THAT DEFECTS WILL BE CORRECTED; OR THAT THE SERVICE OR THE SERVER THAT MAKES THE SERVICE AVAILABLE IS FREE FROM ANY HARMFUL COMPONENTS, INCLUDING, WITHOUT LIMITATION, VIRUSES. THE CR PARTIES DO NOT MAKE ANY REPRESENTATIONS OR WARRANTIES THAT THE INFORMATION (INCLUDING ANY INSTRUCTIONS) ON THE SERVICE IS ACCURATE, COMPLETE, OR USEFUL OR THAT YOU WILL RECEIVE ANY ANTICIPATED SAVINGS. YOU ACKNOWLEDGE THAT YOUR USE OF THE SERVICE IS AT YOUR SOLE RISK. THE CR PARTIES DO NOT WARRANT THAT YOUR USE OF THE SERVICE IS LAWFUL IN ANY PARTICULAR JURISDICTION, AND THE CR PARTIES SPECIFICALLY DISCLAIM SUCH WARRANTIES. SOME JURISDICTIONS LIMIT OR DO NOT ALLOW THE DISCLAIMER OF IMPLIED OR OTHER WARRANTIES SO THE ABOVE DISCLAIMER MAY NOT APPLY TO YOU TO THE EXTENT SUCH JURISDICTION'S LAW IS APPLICABLE TO YOU AND THESE TERMS.</p>
    <p>THE CR PARTIES DO NOT ENDORSE CONTENT AND SPECIFICALLY DISCLAIM ANY RESPONSIBILITY OR LIABILITY TO ANY PERSON OR ENTITY FOR ANY LOSS, DAMAGE (WHETHER ACTUAL, CONSEQUENTIAL, PUNITIVE OR OTHERWISE), INJURY, CLAIM, LIABILITY OR OTHER CAUSE OF ANY KIND OR CHARACTER BASED UPON OR RESULTING FROM ANY CONTENT.</p>
    <h2>Indemnification</h2>
    <p>BY AGREEING TO THESE TERMS YOU AGREE TO INDEMNIFY, DEFEND, AND HOLD HARMLESS THE CR PARTIES FROM AND AGAINST ANY AND ALL CHARGES, CLAIMS, DAMAGES, LOSSES, COSTS, LIABILITIES, AND EXPENSES (INCLUDING ATTORNEYSâ€™ FEES) INCURRED AS A RESULT OF OR ARISING FROM ANY CLAIM, COMPLAINT, ALLEGATION, LAWSUIT OR DEMAND ARISING OUT OF OR RELATING IN ANY WAY TO (A) YOUR ACCESS TO OR USE OF THE SERVICE; (B) YOUR CONTENT OR ANY CONTENT POSTED, UPLOADED, USED, DISTRIBUTED, STORED, OR OTHERWISE TRANSMITTED THROUGH YOUR ACCOUNT; (C) YOUR VIOLATION OF THESE TERMS; (D) YOUR VIOLATION OF THE RIGHTS OF ANOTHER, INCLUDING WITHOUT LIMITATION, ANY INTELLECTUAL PROPERTY RIGHT, PUBLICITY, CONFIDENTIALITY, PRIVACY, OR PROPRIETARY RIGHT; OR (E) YOUR VIOLATION OF ANY STATUTES, CODES, ORDINANCES, LAWS, RULES, REGULATIONS, INCLUDING WITHOUT LIMITATION, ALL REGULATORY, ADMINISTRATIVE, AND LEGISLATIVE AUTHORITIES.</p>
    <h2>Limitation of Liability</h2>
    <p>EXCEPT WHERE PROHIBITED BY LAW, IN NO EVENT WILL CR OR THE CR PARTIES BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL, PUNITIVE, INCIDENTAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES THAT RESULT FROM (A) THE USE OF, OR INABILITY TO USE, THE SERVICE; (B) THE PROVISION OF THE SERVICE OR ANY MATERIALS AVAILABLE THEREIN; OR (C) THE CONDUCT OF OTHER USERS OF THE SERVICE, EVEN IF CR HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. YOU ASSUME TOTAL RESPONSIBILITY FOR YOUR USE OF THE SERVICE. YOUR ONLY REMEDY AGAINST CR FOR DISSATISFACTION WITH THE SERVICE OR ANY CONTENT IS TO STOP USING THE SERVICE. NOTWITHSTANDING THE FOREGOING, IN NO EVENT WILL CRâ€™S LIABILITY TO YOU EXCEED $100.00 FOR ANY DAMAGE OR LOSS THAT ARISES OUT OF OR IS IN ANY WAY CONNECTED WITH THESE TERMS OR YOUR USE OF THE SERVICE OR ANY CONTENT, EVEN IF SUCH AMOUNT SHOULD FAIL OF ITS ESSENTIAL PURPOSE. SOME JURISDICTIONS DO NOT ALLOW LIMITATIONS OF LIABILITY, SO THE FOREGOING LIMITATION MAY NOT APPLY TO YOU.</p>
    <h2>Dispute Resolution</h2>
    <p><strong>Arbitration Agreement; Class Waiver; Waiver of Trial by Jury</strong></p>
    <p>PLEASE READ THE FOLLOWING PARAGRAPHS CAREFULLY BECAUSE THEY REQUIRE YOU TO ARBITRATE DISPUTES WITH CR AND LIMIT THE MANNER IN WHICH YOU CAN SEEK RELIEF FROM US.</p>
    <h2>Applicability of Arbitration Agreement</h2>
    <p>All claims and disputes between the parties that cannot be resolved informally must be resolved by binding arbitration on an individual basis under the terms set forth below (the "Arbitration Agreement"). Notwithstanding the foregoing, in the event of any actual, alleged or threatened violation of confidentiality or violation of the other partyâ€™s intellectual property or other proprietary rights, the non-breaching party may immediately resort to court proceedings in a court of competent jurisdiction as set forth below in order to seek immediate equitable relief without posting of a bond, proof of damages or other similar requirement.</p>
    <p>This Arbitration Agreement applies to you and CR, and to any subsidiaries, affiliates, agents, employees, predecessors in interest, successors, and assigns, as well as all authorized or unauthorized users or beneficiaries of Service provided under the Terms.</p>
    <p>The arbitration proceeding will be administered by JAMS pursuant to its Streamlined Arbitration Rules and Procedures before an arbitrator selected by and pursuant to the rules of JAMS. Any final award may be filed and enforced in any court of competent jurisdiction. The parties shall share equally in the costs assessed for the arbitration. Any such arbitration will take place at a location within the United States federal judicial district identified below and will apply the substantive law set forth below. Any arbitration proceeding may not be consolidated or joined with any other proceeding and will not proceed as a class action. THE PARTIES UNDERSTAND THAT THEY WOULD HAVE HAD A RIGHT OR OPPORTUNITY TO LITIGATE DISPUTES THROUGH A COURT, TO HAVE A JUDGE OR JURY DECIDE THEIR CASE, AND TO PARTICIPATE IN A CLASS ACTION OR OTHER PROCEEDING INVOLVING MULTIPLE CLAIMANTS, BUT THEY CHOOSE TO HAVE ANY DISPUTES DECIDED THROUGH INDIVIDUAL ARBITRATION.</p>
    <p>The decision of the arbitrator will be a final and binding resolution of the dispute. This Arbitration Agreement is made pursuant to a transaction involving interstate commerce and will be governed by the Federal Arbitration Act, 9 U.S.C. Sections 1â€“16. Judgment upon the award may be entered in any court having jurisdiction.</p>
    <h2>Survival</h2>
    <p>This provision will survive the termination of your relationship with CR.</p>
    <h2>Time Limitation on Claims</h2>
    <p>You agree that any claim you may have arising out of or related to your relationship with CR must be filed within one year after such claim arose; otherwise, your claim is permanently barred.</p>
    <h2>Forum and Venue</h2>
    <p>A lawsuit, if any, by you or CR against the other will occur in state or federal court in Texas. You and CR agree that the jurisdiction and venue of these courts is exclusive.</p>
    <h2>Applicable Law</h2>
    <p>Any dispute between you and CR will be governed by the laws of the State of Arizona and applicable United States law, without giving effect to any conflict-of-laws principles that may provide for the application of the law of another jurisdiction.</p>
    <h2>Severability</h2>
    <p>If any provision of these Terms shall be deemed unlawful, void or for any reason unenforceable, then that provision shall be deemed severable from these Terms and shall not affect the validity and enforceability of any remaining provisions.</p>
    <h2>Entire Agreement</h2>
    <p>These Terms supersede all prior understandings regarding the Services and represent the complete agreement between you and CR. These Terms do not create or confer any third-party beneficiary rights. We may, at our sole discretion, change or modify these Terms at any time. If we make changes to these Terms, we will provide notice of such changes, such as by sending a notification, posting a notice on the Service, or updating the "Last Updated" date above. Your continued use of the Service will confirm your acceptance of the updated Terms. We encourage you to frequently review the Terms to ensure you understand the terms and conditions that apply to your use of the Service. If you do not agree to the revised Terms, you must stop using the Service and delete your CR account.</p>
    <h2>Contacting Us</h2>
    <p>If you have any other questions or concerns regarding these Terms of Service, please contact us as follows:</p>
    <p>Via email at: <a href="mailto:customercare@ComplianceReward.com">customercare@ComplianceReward.com</a><br>
    Or by Mail at:<br>
    Compliance Reward, LLC<br>
    3201 Fannin Lane;<br>
    Southlake, TX 76092</p>
</div></div>


    @endsection