@extends('layouts.compliance')
@section('content')
<section class="main-wrapper">
    <div class="container height_fullp grid_width">
        <div class="row height_fullp">
            <div class="col-sm-12">


<style>
    #terms-service{/*font-family: Roboto, sans-serif;*/padding-bottom: 70px; color: #242424;}
    
    #terms-service h3 { font-size: 24px; margin: 24px 0px; font-weight: 600; }
    
    #terms-service p{font-size: 18px; line-height: 1.4em; margin: 14px 0px;}
    #terms-service p span { font-size: inherit; line-height: inherit; }
    
    #terms-service ul { list-style-type: disc; list-style-position: outside; padding-left: 40px; }
    #terms-service ul li{font-size: 18px; line-height: 1.4em; margin-bottom: 7px;}
    #terms-service ul li span { font-size: inherit; line-height: inherit; }
    
    #terms-service .uppercase_bold{text-transform: uppercase;font-weight:600;}
    
    #terms-service a { font-size: inherit; color: #3e7bc4; text-decoration: underline; display: inline-block; vertical-align: baseline; }
    #terms-service a:hover {  color: #007bff !important;}
    
    .bottom-solid-line { margin-left: 7px; margin-right:7px; border-bottom: solid 2px #242424;width: 100px;display: inline-block;height: 1.04em;}
    
</style>

<div class="row">
<div class="col-sm-12">
    
    <div id="terms-service">
        <h3>ComplianceReward℠ Terms of Service</h3>
        <p class="weight_600">Last Updated on March 26, 2020</p>
        <p>The ComplianceReward℠ Service ("Service”) is owned and operated by Ingenious Mobility Ventures, LLC ("IMV"). The Service is a prescription drug program where patient participants who adhere to their medications, pursue digital advisories and education to positively affect their health earn tokens associated with their ComplianceReward℠ card/wallet tied to their patient Account. The Service includes participants who are enrolled as providers ("Providers"). Providers include Physicians, Pharmacists and the associated medical practices. They are enrolled, have accounts and participate in the ComplianceReward℠ ecosystem to promote health, facilitate access to pharmacies, physicians and associated medical practices.</p>
        <p>The Service is NOT a health insurance policy and is not intended as a substitute for health insurance. The Service allows you to earn tokens and apply them for prescription drugs purchased through participating providers. The patient is required to pay for all prescription drugs at the time of purchase. You will need to present your ComplianceReward℠ card/wallet before you pay for any prescription. You can earn tokens for your ComplianceReward℠ card/wallet and apply them for prescription drugs purchased through participating providers. IMV does not make payments to any pharmacy or health care provider through the Service. A listing of participating pharmacies is available at <a href="https://www.ComplianceReward.com">www.ComplianceReward.com</a>.</p>
        <p>The Service is administered by Ingenious Mobility Ventures, LLC located at 9001 Airport Freeway, North Richland Hills, TX 76180. See, <a href="https://www.ComplianceReward.com">www.ComplianceReward.com</a>.</p>
        <p>You may cancel your Account or file a complaint regarding the Service at any time by contacting Customer Care  at <a href="mailto:customercare@ComplianceReward.com">customercare@ComplianceReward.com</a> </p>
        <p>Please read these Terms of Service ("Terms") carefully. These Terms are a binding electronic contract between you and Ingenious Mobility Ventures, LLC ("IMV", "Company", "we", "us" or "our") governing the registration and use of our ComplianceReward℠ services as described below ("Service"). By participating in, registering for or using the Service via the ComplianceReward℠ mobile application ("Application") or website <a href="https://www.ComplianceReward.com">www.ComplianceReward.com</a> ("Website") you agree to be bound by these Terms. These Terms affect your legal rights and obligations, so if you do not agree to these Terms, do not enroll, register or use the Service.</p>
        <p><span class="weight_600 tt_uc_">NO MEDICAL ADVICE:</span> Neither the Website, the Application, nor the Services should be used for medical problems or conditions. If you have or suspect that you have a medical problem or condition, please contact a qualified health care professional immediately. If you are in the United States and are experiencing a medical emergency, please call 911 or call for emergency medical help on the nearest telephone.</p>
        <p clas="tt_uc_">ARBITRATION NOTICE: EXCEPT FOR CERTAIN TYPES OF DISPUTES DESCRIBED IN THE ARBITRATION CLAUSE BELOW, YOU AGREE THAT DISPUTES BETWEEN YOU AND IMV WILL BE RESOLVED BY MANDATORY BINDING ARBITRATION AND YOU WAIVE ANY RIGHT TO PARTICIPATE IN A CLASS-ACTION LAWSUIT OR CLASS-WIDE ARBITRATION.</p>
        <h3>Privacy</h3>
        <p>Your privacy is important to us. The Compliance Rewards Privacy Policy is incorporated into these Terms by reference. By accepting these Terms, you agree to the collection, use, and sharing of your information, including your content, through the Service in accordance with the Compliance Rewards  Privacy Policy, at <a href="http://www.ComplianceReward.com/Privacy">http://www.ComplianceReward.com/Privacy</a>.</p>
        <h3>Modifications to these Terms</h3>
        <p>We may, at our sole discretion, revise these Terms from time to time. The most current version of these Terms will be made available to you on the Website and will be linked to from within the Application. We encourage you to periodically review these Terms. If we make material changes to these Terms, we will notify you on the Website or within the Application or both by posting a conspicuous notice on the Services or by otherwise sending you a notification prior to the effective date of the changes. By continuing to access or use the Services after those changes become effective, you agree to be bound by the revised Terms. If you do not agree to the revised Terms, you may terminate your account as set forth below.</p>
        <h3 class="uppercase_bold">Online Health Initiative Survey</h3>
        <p>IMV may offer the opportunity to participate in an Online Health Initiative Survey, which will request from you certain information on medical and other conditions. Your answers to an online Health Initiative Survey will allow us to send you educational information on certain medical conditions as well as information on additional savings opportunities related to the treatment of those medical conditions. THE ONLINE HEALTH INITIATIVE SURVEY SERVICE PROVIDED THROUGH THE APPLICATION IS DIFFERENT FROM THE DIAGNOSTIC SERVICES TYPICALLY PROVIDED BY A PHYSICIAN AND THE RESULTS SHOULD NOT BE CONSIDERED AS THE ADVICE OF A HEALTH CARE PROFESSIONAL. This service will not have the benefit of information that would be obtained by examining you in person and observing your physical condition. Therefore, the Online Health Initiative Survey results may not take into account particular facts or information that would affect a physician's opinion of your medical condition. In some cases, the facts may be critical to the opinion.</p>
        <p class="uppercase_bold">BY DECIDING TO ANSWER ANY ONLINE HEALTH INITIATIVE SURVEY, YOU ACKNOWLEDGE AND AGREE THAT THE ONLINE HEALTH INITIATIVE SURVEY IS NOT INTENDED TO REPLACE A FULL MEDICAL EVALUATION OR A FACE-TO-FACE VISIT WITH A PHYSICIAN. FURTHER, YOU ACKNOWLEDGE AND AGREE TO SOLELY ASSUME THE RISK OF THESE LIMITATIONS AND FURTHER UNDERSTAND THAT NO WARRANTY OR GUARANTEE HAS BEEN MADE TO YOU CONCERNING ANY PARTICULAR RESULT OR CURE OF YOUR CONDITION.</p>
        <h3>General Conditions</h3>
        <ul>
            <li>Use of the Services via the Application requires the download of the Application from the Apple iTunes App Store or the Google Play Store. Download of any Application is subject to the applicable End User License Agreement. You may also register for and use the Service through the Website.</li>
            <li>If you choose to create an account you will be required to provide us with your name, email address, date of birth and zip code to submit your registration and open your account ("Account"). Information that we collect during registration will be used as set forth in our Privacy Policy.</li>
            <li>You must be at least 13 years old to use the Service.</li>
            <li>IMV prohibits the creation of and you agree that you will not create an Account for anyone other than yourself. You also represent that all information you provide to IMV upon registration and at all other times will be true, accurate, current and complete and you agree to update your information as necessary to maintain its truth and accuracy.</li>
            <li>We reserve the right to refuse access to the Service to anyone for any reason at any time.</li>
            <li>We reserve the right to force forfeiture of any username for any reason.</li>
            <li>You agree that you are responsible for all data charges and/or SMS charges you incur through use of the Service.</li>
        </ul>
        <h3>Modifications to Services</h3>
        <ul>
            <li>We reserve the right to modify or terminate the Service or your access to the Service for any reason, at any time, and without liability to you.</li>
        </ul>
        <h3>Termination of Your Account</h3>
        <ul>
            <li>You can deactivate your Account within the settings of the Service or by requesting the deactivation of your account at <a href="mailto:info@ComplianceReward.com">info@ComplianceReward.com</a>.</li>
            <li>We may also terminate your access to the Service if we believe you have materially breached these terms or your use of the Services otherwise presents any legal or other risk to IMV or any third party.</li><li>
            </li><li>If we terminate your access to the Service or if you request the deactivation of your account by emailing the address above, your data will no longer be accessible through your Account.</li>
            <li>Upon termination, all licenses and other rights granted to you in these Terms will immediately cease.</li>
            <li>There may be links embedded in the Service, or from images or content within the Service, to third party websites or features. We do not control, maintain or endorse any content or materials provided by any third party. If you choose to access such third-party websites or materials you do so at your own risk. We encourage you to visit the terms and policies applicable to such websites and materials.</li>
        </ul>
        <h3>Using the Patient Account</h3>
        <div class="trow_" style="padding-left: 40px;">
            <p>The patient authorizes the use of a third-party application RxDirect Metro Delivery℠ or a licensed white label product RXRun℠ developed by Ingenious Mobility Ventures LLC and voluntarily provides patient name, shipping address, date of birth, insurance information, co-pay assistance cards and medications they seek transferred from another pharmacy. </p>
            <p>The patient grants explicit permission for IMV to share elements of a prescription and health information with dispensing pharmacies and sponsors in order to safely coordinate the delivery and advisories and to receive compliance sponsorship. These elements include medication names, quantity refills, Prescriber name, reimbursement data, current refills, drug information and results of surveys or outreach performed by payer details. </p>
            <p>The patient permits IMV to contact them in a secure and direct nature about information pertaining to recalls, shortages, proactive patient safety and proper use advisories, notification of refills or the expiration of a prescription, lower cost alternatives and to conduct surveys or confirmation as part of a compliant support program. </p>
            <p>The patient acknowledges enrollment in ComplianceReward℠ by IMV  to establish a bank of "points" provided by IMV and various sponsors, to retain a virtual wallet on their behalf to distribute payment to applicable service providers</p>
            <p>For example, a dispensing pharmacy or medical marketplace partner may receive a distribution from the pointe balance in the form of cash where a sponsor allows. IMV will keep an accounting of payments made on behalf of member in a year end statement.</p>
        </div>
        <h3>Use of Your Account</h3>
        <ul>
            <li>You acknowledge and agree that you do not have any ownership or other property interest in your Account. Your Account and all rights in your Account are owned by IMV. However, subject to your compliance with these Terms, you are allowed to use your Account as set forth in these Terms</li>
            <li>You are responsible for any activity that occurs through your Account. You are solely responsible for all transactions and activities undertaken by anyone utilizing your Account or your ComplianceReward℠ card, whether authorized or unauthorized. This includes any and all purchases, authorized or unauthorized, made from pharmacies.</li>
            <li>You must immediately notify IMV of any suspected unauthorized transactions associated with your Account or your ComplianceReward℠ card or any other breach of security.</li>
            <li>You may not sell, transfer, license or assign your Account, username, or any Account rights to anyone</li>
            <li>You are responsible for keeping your password secret and secure.</li>
            <li>You understand and agree that you use the Service at your own risk.</li>
            <li>BY ACCESSING OR USING THE SERVICE YOU REPRESENT AND WARRANT THAT YOUR ACTIVITIES ARE LAWFUL IN EVERY JURISDICTION WHERE YOU ACCESS OR USE THE SERVICE.</li>
        </ul>
        <h3>Prohibited Activities</h3>
        <p>In addition to the other restrictions outlined in these Terms, you agree that you will not:</p>
        <ul>
            <li>Use the Service for any purpose that is illegal, unauthorized, beyond the scope of its intended use, or engage in, encourage, promote, advocate or assist any third party in any activity that violates these Terms or is otherwise prohibited in these Terms or the terms of any third party that govern a particular Service;</li>
            <li>Interfere with or disrupt servers or networks used by IMV to provide the Service or used by other users to access the Service, or violate any third party regulations, policies or procedures of such servers or networks or harass or interfere with another user's full use and enjoyment of the Service;</li>
            <li>Send any unsolicited or unauthorized advertising, spam, solicitations, or promotional materials to other users of the Service;</li>
            <li>Solicit or attempt to solicit personal information from other users of the Service;</li>
            <li>Intercept, examine, monitor or otherwise observe any proprietary communications protocol used by a device, a client or a server communicating with the Service, whether through the use of a network analyzer, packet sniffer or other device or software, unless expressly authorized by the company;</li>
            <li>Use any robot, bot, spider, crawler, scraper, or other automated means or interface not provided by us to access the Service or to extract data;</li>
            <li>Reverse engineer, decompile, disassemble, decipher or otherwise attempt to derive the source code for any underlying software or other intellectual property used to provide the Service or circumvent measures employed to prevent or limit access to any area, content, or source code of the Service;</li>
            <li>Use or attempt to use another user’s account without authorization;</li>
            <li>Attempt to compromise any security measures or circumvent any content-filtering techniques we employ, or attempt to access areas or features of the Service that you are not authorized to access;</li>
            <li>Attempt to represent in any manner that you have a relationship of any kind with us or that we have endorsed you or any products or services without our express written consent to do so;</li>
            <li>Engage in or encourage, promote, advocate or assist any third party in any harassing, bullying, intimidating, predatory, or stalking activities;</li>
            <li>You may not post violent, nude, partially nude, discriminatory, unlawful, infringing, hateful, pornographic or sexually suggestive photos or other similar content via the Service;</li>
            <li>Impersonate any person or entity or otherwise misrepresent your affiliation with a person or entity;</li>
            <li>Make available any content that infringes the rights of any person or entity, including without limitation, any patent, trademark, trade secret, copyright, privacy, publicity or other proprietary or contractual rights;</li>
            <li>Reproduce, duplicate, copy, buy, sell, trade, resell or exploit for any commercial purpose any portion of the Service, including your Account, Company Materials (as defined below), or access to or use of the Service or Company Materials without our prior written consent; and</li>
            <li>Develop any third party applications that interact with other users of the Service or the Service without prior written consent from IMV.</li>
        </ul>
        <p>The ComplianceReward℠ logo, and other IMV trademarks, service marks, graphics and logos used in connection with the Service are trademarks or registered trademarks of IMV or its affiliates (collectively "IMV Marks"). Third party trademarks, service marks, graphics and logos used in connection with the Application are the trademarks of their respective owners (collectively "Third-Party Marks"). The IMV Marks and Third-Party Marks may not be copied, imitated or used, in whole or in part, without the prior written permission of IMV or the applicable trademark holder</p>
        <p>Unless otherwise stated, all materials contained on or within the Service, the Application or the Website that are provided by IMV, including, but not limited to, text, graphics, images, code, illustrations, designs, icons, photographs, and written and other materials (collectively, "Company Materials"), as well as their selection and arrangement, are protected by copyright, trademark, trade dress, patent, and/or other intellectual property laws.</p>
        <p>Subject to your compliance with these Terms, IMV grants you a limited, nonexclusive, non-sub-licensable license to access and use the Service and Company Materials solely as made available in the Application or Website. This license is revocable at any time as further contemplated by these Terms. You may not:</p>
        <ul>
            <li>Distribute, publicly perform or publicly display any Company Materials;</li>
            <li>Modify or make any derivative uses of the Service or Company Materials, or any portion thereof;</li>
            <li>Download any portion of the Service, Company Materials, or any information contained therein, except as expressly permitted by the Service;</li>
            <li>Copy, reproduce, republish, frame, download, transmit, modify, display, reverse engineer, sell, or participate in any sale of, rent, lease, loan, assign, distribute, license, sublicense, or exploit in any way, in whole or in part, Company Materials, the Service, the Application, the Website or any related software, except as expressly stated in these Terms; or</li>
            <li>Otherwise use the Service or Company Materials other than for their intended purposes.</li>
        </ul>
        <p>You may not use Company Materials in any manner except as necessary to use the Services as provided by IMV. IMV does not grant you any other right or license to use the Company Materials. Unauthorized use of Company Materials is a violation of these Terms, which may result in the termination of your Account, and may constitute a violation of applicable federal and state laws.</p>
        <p>Location Services: The ComplianceReward service may have features that make use of your geolocation data. You consent to our collection and use of your geolocation data, if you click to permit the mobile application access to such data or if you click to accept these Terms. Section Q and the Privacy Policy apply when you allow access to your geolocation data.</p>
        <h3>ComplianceReward Service: Patients Representations</h3>
        <p>By using the ComplianceReward service as a patient, you represent that you are at least eighteen (18) years of age, and if you are not, you may only use the ComplianceReward service with the full and express consent of your parent or legal guardian, or else you must immediately stop using the ComplianceReward service. You acknowledge that your use of the ComplianceReward service contemplates our receipt and use of personally identifiable information relating to minors under the age of eighteen (18) years ("Minors"). If you are using the ComplianceReward service on behalf of a Minor, you represent that you are fully authorized to accept these Terms and use the ComplianceReward service on such Minor’s behalf, and to provide us with personal and health information about such Minor. Any other use is unauthorized and constitutes an infringement and violation of these Terms and of IMV’ intellectual property and other rights.</p>
        <h3>Patient Enrollment</h3>
        <p>We may also require you to create and use an account with IMV to use all or certain features of the ComplianceReward services. For instance, to access Providers for telemedicine consultations, you must first establish an individual user account (an "Account") by providing us with certain information. You agree that you will not create more than one Account, or create an Account for anyone other than yourself (with the exception of subaccounts established for minor children of whom you are a parent or legal guardian). You agree to provide true, accurate, current, and complete information when creating your Account and that you will update such information as needed thereafter. If you provide any information which is untrue, inaccurate, not current or incomplete, or if we have reasonable grounds to suspect that such Account information is untrue, inaccurate, not current, or incomplete, we reserve the right to suspend or terminate your Account and refuse to provide you any and all current or future use of the ComplianceReward service</p>
        <h3>Physician Enrollment</h3>
        <p>We require you to create and use an account with IMV to activate the practice and physician  features of the ComplianceReward services. For instance, providers for telemedicine consultations, you must first establish an individual user account (an "Account") by providing us with certain information. You agree that you will not create more than one Account, or create an Account for anyone other than yourself You agree to provide true, accurate, current, and complete information when creating your Account and that you will update such information as needed thereafter. If you provide any information which is untrue, inaccurate, not current or incomplete, or if we have reasonable grounds to suspect that such Account information is untrue, inaccurate, not current, or incomplete, we reserve the right to suspend or terminate your Account future use of the ComplianceReward service. </p>
        <h3>Pharmacy Enrollment</h3>
        <p>We require you to create and use an account with IMV to use pharmacy and practice  features of the ComplianceReward services.  ____________________________________________</p>
        <p>_____________________________________________________________</p>
        <p>_______________________________________________________________________. You agree that you will not create more than one Account, or create an Account for anyone other than yourself (with the exception of subaccounts established for minor children of whom you are a parent or legal guardian). You agree to provide true, accurate, current, and complete information when creating your Account and that you will update such information as needed thereafter. If you provide any information which is untrue, inaccurate, not current or incomplete, or if we have reasonable grounds to suspect that such Account information is untrue, inaccurate, not current, or incomplete, we reserve the right to suspend or terminate your Account and future use of the ComplianceReward service.</p>
        <h3>ComplianceReward is NOT Medical Advice or Application</h3>
        <p><span class="uppercase_bold">Notice to patient participants</span>&nbsp;ComplianceReward services are not intended to function as a medical application or service. Some of our ComplianceReward services may be used to connect you with a Provider for a telemedicine consultation. IMV does not provide any health care services itself. Providers may use the ComplianceReward service as a platform to communicate with you. All information or advice received from a Provider comes from the Provider, and not from IMV. You acknowledge and agree that IMV is not engaged in the practice of medicine and that IMV does not determine appropriate medical use of the ComplianceReward service. Neither IMV nor any of its licensors, suppliers or any third parties who promote the ComplianceReward service or provide you with a link to the ComplianceReward service shall be liable for any professional advice you obtain from a Provider via the ComplianceReward service, including but not limited to liability for medical malpractice. You acknowledge that your reliance on any Providers or information provided by the ComplianceReward service is solely at your own risk and you assume full responsibility for all risk associated therewith. IN THE EVENT OF ANY MEDICAL EMERGENCY OR OTHER EMERGENCY SITUATION, YOU WILL NOT RELY ON THE COMPLIANCEREWARD SERVICE, AND INSTEAD YOU WILL CONTACT A HOSPITAL, LOCAL 911 SERVICES, URGENT CARE PROVIDER OR YOUR OR YOUR MINOR’S PHYSICIAN.</p>
        <p>IMV does not make any representations or warranties about the training or skill of any Providers you may access via the ComplianceReward service. You are ultimately responsible for choosing your particular Provider on the ComplianceReward service. You hereby certify that you are physically located in the State you entered as your current location in your Account or otherwise specified on the ComplianceReward service. You acknowledge that your ability to access and use the ComplianceReward service is conditioned upon the truthfulness of this certification and that the Providers you access through the ComplianceReward service are relying upon this certification in order to interact with you. If your certification is inaccurate, you agree to indemnify us and the Providers you interact with from any resulting damages, costs or claims. The Providers affiliated with IMV are licensed to practice medicine in the locations identified in the ComplianceReward service, and neither the Providers nor IMV intend to solicit patients from other states in which the Providers are not licensed. Other than information and communications received directly from Providers, you acknowledge and agree that the ComplianceReward services are not intended for any of the following uses: diagnosis of disease or other conditions; the cure, mitigation, treatment, or prevention of disease; or to affect the structure or any function of the human body. Any health tips, blog postings (including the "Dear Dr. Christina" column) or other health-related information provided through the ComplianceReward service are of a general informative nature, not to be used in any diagnosis or treatment.</p>
        <h3>Scope of License</h3>
        <p>IMV grants you as a patient or a provider with a  limited, non-exclusive, non-transferable, revocable right to use the particular ComplianceReward service functionality and features permissioned for you and provided therein solely in connection with the purposes for which the ComplianceReward service was designed. You may download, view and/or run a copy of the ComplianceReward service on one or more of your mobile devices or computers, solely to use the features and information provided therein for the purposes for which they were designed. You agree that all features of the ComplianceReward service may not work well or at all on any device or computer.</p>
        <h3>Restrictions</h3>
        <p>You may not do any of the following: (1) distribute or make the ComplianceReward service available over a network where it could be used by multiple devices at the same time; (2) rent, lease, lend, sell, redistribute, sublicense, act as a service bureau, or grant rights in the ComplianceReward service; (3) copy, decompile, reverse engineer, disassemble, attempt to derive the source code of, modify, or create derivative works of the ComplianceReward service, any updates, or any part thereof; (4) intercept, examine or otherwise observe any proprietary communications protocol used by the ComplianceReward service, whether through the use of a network analyzer, packet sniffer or other device; (5) use any type of bot, spider, virus, clock, timer, counter, worm, software lock, drop dead device, Trojan horse routing, trap door, time bomb or any other codes, instructions or third party software that is designed to provide a means of surreptitious or unauthorized access to, or distort, delete, damage or disassemble, the ComplianceReward service or any website, application or service organized or provided by IMV or existing on any of our network hardware or infrastructure; (6) use the ComplianceReward service to institute, assist, or become involved in any type of attack, including denial of service attacks, upon any party; (7) commit trespass or act in a manner that intentionally burdens network capacity; (8) use the ComplianceReward service in any manner to harass, abuse, stalk, threaten, defame or otherwise infringe or violate the rights of any other party; (9) provide us sensor data (such as microphone, camera, fitness or other data) that you are not authorized to provide; or (10) engage in any other conduct that restricts or inhibits any person from using or enjoying the ComplianceReward service or that, in our sole judgment, exposes us or any of our users, affiliates, or any other third party to any liability, damages, or detriment of any type. Any attempt to do any of the foregoing is a breach of these Terms and automatically subjects you to any and all claims and liability available under the law, including without limitation contract breach and intellectual property infringement. If you breach any of these restrictions, you may be subject to prosecution and damages. These Terms will govern any upgrades provided by IMV that replace and/or supplement the ComplianceReward service.</p>
        <h3>Privacy; Collection and Transmission of Data and Information</h3>
        <p>Our Privacy Policy is available on our website at <a href="http://www.compliancereward.com/home/privacy-policy/">Compliancereward.com/home/privacy-policy/</a>, as such site and policy may be updated from time to time but accessible from our home page at <a href="www.ComplianceReward.com">www.ComplianceReward.com</a> or as we may otherwise notify you. You agree that IMV may collect, use and disclose information and data as described in the Privacy Policy and that is gathered periodically to facilitate the provision of software updates, product support and other services to you related to the ComplianceReward service or any of its features. When you provide information using the ComplianceReward service, that information may be transmitted over the internet to systems organized by IMV or agents acting on its behalf. You hereby consent to all such transmissions and acknowledge that information exchanged over the Internet may in some cases be intercepted and read by third parties. Subject to the Privacy Policy, IMV shall have no responsibility for any such interception.</p>
        <p>You are solely responsible for the security of your Account username and password. You should not share your username and password with any third party or allow any third party to access the ComplianceReward service using your username and password. You agree to notify us if you have any reason to believe that your username or password has been lost, compromised, or misused in any manner. You will be solely and fully responsible for any damage to the ComplianceReward service or any computer system, any loss of data, or any improper use or disclosure of information on the ComplianceReward service caused by you or any person using your username or password. We reserve the right to revoke or deactivate your username and password at any time, for any reason or no reason.</p>
        <p>Use of certain features of our mobile application may require enabling access to information provided by your mobile device. For example, ComplianceReward services may use geolocation data to find a provider near you, and it may access your phone dialer to call a location. Other features may add appointments to your calendar or access your camera, phone or other sensor data. If you do not grant the mobile application access, then these features may work partially or not at all. IMV disclaims any warranty that any feature will be available on any particular device.</p>
        <h3>Consent to Receive Text Messages</h3>
        <p>Some of our ComplianceReward services have a feature that sends messages to your wireless phone or device, for example, reminding you of an appointment, updating you about your appointment status and wait time or seeking your feedback following a consultation or visit. If the ComplianceReward service has a feature to send you SMS text messages and you provide your mobile telephone number to us, you agree that the act of providing your mobile telephone number to us constitutes your consent to receive SMS text messages from IMV or on our behalf and you acknowledge that your wireless or mobile carrier may apply extra charges and fees. You may revoke this communication authorization at any time by completing and submitting the form below.</p>
        <h3>Patient Payments</h3>
        <p>ComplianceReward services, such as telemedicine consultations, require you to pay a fee prior to accessing the ComplianceReward service or following a visit or consultation. Similarly, an ComplianceReward service may facilitate your ability to make payments to IMV for products and services provided to you separately from the mobile application and billed to an account that you may have with IMV or billed to your health insurance provider. By authorizing any payment through the ComplianceReward service, you agree to these payment terms.</p>
        <h3>Physician Payments</h3>
        <p>______________________________________________________________________________________________________________________________</p>
        
        <h3>Pharmacy Payments</h3>
        
        <p>You agree that ensuring and confirming all necessary payments remains your sole responsibility. IMV shall have no responsibility for failure of the ComplianceReward service to transmit payments on time, and we are not and cannot be responsible for any inaccuracy, error, delays, omission, non-performance, interruption or other failure of any data, information or message caused by flaws or other problems with the ComplianceReward service, Internet outages, network delays, interceptions of data or information, changes in third party payment processors and processing networks, bank restrictions, other similar events or conditions, or any "force majeure" events that may prevent your payment requests from being fulfilled. TO THE EXTENT THAT INABILITY TO PAY YOUR BILLS ON TIME USING THE COMPLIANCEREWARD service CAUSES YOU TO INCUR ANY FEES OR PENALTIES, OR EXPOSES YOU TO LIABILITY OR OTHER CLAIMS BY A GOVERNMENTAL AUTHORITY OR ANY THIRD PARTY, YOU AGREE TO RELEASE IMV AND HOLD IMV HARMLESS FROM ANY AND ALL RESPONSIBILITY FOR SUCH INABILITY TO PAY.</p>
        <p>By providing a credit card or other payment method accepted by IMV (the "Payment Method"), you expressly agree that IMV is authorized to charge to the Payment Method any fees for your use of the ComplianceReward service and any applicable taxes. If the ComplianceReward service is covered by your health insurance plan, please be aware that IMV may not receive complete information from such health insurance plan about the applicable co-payment amount you owe at the time the ComplianceReward service is rendered. Accordingly, IMV may bill you more than once with respect to a given consultation to account for additional co-payment amounts due, if any. You agree that authorizations to charge the Payment Method remain in effect until you cancel it in writing, and you agree to update IMV regarding any changes to the Payment Method. You certify that you are an authorized user of the Payment Method and will not dispute charges from us that correspond to consultation fees or co-payment amounts required by your health insurance plan for use of the ComplianceReward service. In the event that amounts charged to the Payment Method are rejected for insufficient funds, IMV may at its discretion attempt to process the charge again at any time within thirty (30) days. You hereby acknowledge that all payments from your account must comply with applicable provisions of federal, state and local law.</p>
        <h3>Suspension; Termination</h3>
        <p>IMV reserves the right to change, suspend, remove, disable or terminate access to the ComplianceReward service at any time without notice, for any or no reason, and with no liability or responsibility to you. IMV may also impose limits on the use of or access to the ComplianceReward service, in any case and without notice or liability. These Terms and your license to use the ComplianceReward service are effective until terminated by you or IMV. You may terminate your agreement with these Terms and your obligations hereunder by ceasing all use of the ComplianceReward service and deleting any mobile or other application related to the ComplianceReward service from each of your devices. If you fail to comply at all times with these Terms, your license to use the ComplianceReward service will terminate automatically and without any notice from IMV, and your continued use after termination exposes you to legal liability to IMV, which IMV may pursue to the fullest extent permitted by law, including the pursuit of monetary damages or injunctive relief at our discretion. Upon any termination of the license, you shall cease all use of the ComplianceReward service and destroy all copies, full or partial, of the ComplianceReward service.</p>
        <h3>WARRANTY</h3>
        <p>You expressly acknowledge and agree that your use of the ComplianceReward service is at your sole risk and that the entire risk as to satisfactory quality, performance, accuracy and effort is with you. The ComplianceReward service and information contained therein is performed or provided "as is" and "as available", with all faults and without warranty of any kind. IMV makes no, and hereby disclaims all, warranties and conditions with respect to the ComplianceReward service, either express, implied or statutory, including, but not limited to: implied warranties and/or conditions of merchantability, of satisfactory quality or performance, of fitness for a particular purpose, of accuracy, currency or completeness of information, of accuracy or currency of geolocation data, of accuracy or currency of driving or transportation directions, of quiet enjoyment, of non-infringement, of functionality, of availability, of network connectivity and transmission, of ability to access or use the ComplianceReward service at the times or locations of your choosing, of quality of translations, of non-interference with your enjoyment of the ComplianceReward service, that the functions contained in, or services performed or provided by, the ComplianceReward service will meet your requirements, that the operation of the ComplianceReward service will be uninterrupted or error-free, that defects in the ComplianceReward service will be corrected, or that the ComplianceReward service is free of viruses or other harmful components. No oral or written information or advice given by IMV or its authorized representative shall create any warranty. IMV cannot and does not assume any responsibility for any loss, damages, or liabilities arising from the failure of any telecommunications infrastructure, or the internet, or for your misuse of any protected health information, advice, ideas, information, instructions, or guidelines accessed through the ComplianceReward service. Some jurisdictions do not allow the exclusion of certain implied warranties or limitations on applicable statutory rights of a consumer, so certain of the above exclusions and limitations may not apply to you.</p>
        <h3>LIMITATION OF LIABILITY</h3>
        <p>To the extent not prohibited by law, in no event shall IMV be liable for personal injury or for any direct, indirect, incidental, special, consequential or similar damages whatsoever, including, without limitation, damages for loss of profits or sales, loss or corruption of data, loss of use of your device, business interruption or any other damages or losses, arising out of or related to your use or inability to use the ComplianceReward service, however caused, regardless of the theory of liability (contract, tort or otherwise) and even if application provider has been advised of the possibility of such damages. Some jurisdictions do not allow the limitation of liability for personal injury, or of incidental or consequential damages, so this limitation may not apply to you. IMV shall have no (zero) liability to you in connection with these terms or the ComplianceReward service, the use of which is provided to you free of charge. If IMV charged a fee for the ability to download, use or view the ComplianceReward service, then the total liability of IMV to you for all damages shall not exceed the amount of fifty united states dollars (us $50.00).</p>
        <h3>Indemnification</h3>
        <p>You agree to indemnify, defend and hold harmless IMV, and its parents, owners, affiliates, subsidiaries, directors, officers, employees, agents, and business partners (collectively, the "Indemnified Parties") from and against any and all claims, actions, proceedings and suits, and all related liabilities, damages, settlements, penalties, fines, costs and expenses (including, without limitation, reasonable attorney’s fees and other dispute resolution expenses) incurred by any Indemnified Party arising out of or relating to your violation or breach of these Terms or misuse of the ComplianceReward service. We reserve the right to assume the exclusive defense of any claim for which we are entitled to indemnification under this Section. In such event, you shall provide us with such cooperation as we reasonably request.</p>
        <h3>Third Party Content, Services and Materials</h3>
        <p>The ComplianceReward service may (1) enable access to services, web sites or platforms (including social media platforms) organized or provided by third parties, or (2) display, include or make available content, data, information, applications or materials from third parties or provide links to certain third party web sites ("Third Party Materials"). The "Dear Dr. Christina" page may invite you to follow Dr. Christina on the Facebook or Twitter social media platforms. Third Party Materials and links to other web sites are provided solely as a convenience to you. By using the ComplianceReward service, you acknowledge and agree that IMV is not responsible for examining or evaluating the content, accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality, language availability, appropriateness, availability or any other aspect of such Third Party Materials. You are responsible for complying with applicable laws and website and online policies for all sites or platforms when you view or use the ComplianceReward service and any Third Party Materials, and also when you use sharing features of the ComplianceReward service to post or share certain content or links on third party platforms. IMV DISCLAIMS ALL EXPRESS AND IMPLIED WARRANTIES REGARDING THIRD PARTY MATERIALS. WE DO NOT ENDORSE OR ASSUME ANY LIABILITY OR RESPONSIBILITY TO YOU OR ANY OTHER PERSON FOR ANY THIRD PARTY MATERIALS.</p>
        <p>Use of all features of the ComplianceReward service may require an Internet access plan, a phone plan, or other third party connectivity service plans, and you are bound by the terms of service of any such third party service plan. IMV does not provide any such service plans and has no responsibility for any such plan.</p>
        <p>Although IMV does not intend for the ComplianceReward service to contain objectionable content, you understand and acknowledge that by using any of the ComplianceReward services, you may encounter content that may be deemed offensive, indecent, or objectionable, which content may or may not be identified as having explicit language, and that the results of any search or entering of a particular URL may automatically and unintentionally generate links or references to objectionable material. Nevertheless, you agree to use the ComplianceReward service at your sole risk and that IMV shall not have any liability to you for content that may be found to be offensive, indecent, or objectionable.</p>
        <h3>Ownership</h3>
        <p>The ComplianceReward service is licensed and not sold. IMV reserves all rights not expressly granted to you by these Terms. The information, text, content, images, videos, data, look and feel, color scheme, logos, and all other material contained on this website are subject to copyright, patent, trademark and other intangible rights protection. You may not use such material except as part of the ComplianceReward service and in accordance with these Terms. No portion of the ComplianceReward service may be reproduced in any form or by any means, except that you may use sharing features available from within the ComplianceReward service (but only to the extent facilitated by such sharing feature). We do not grant you any other rights to such material.</p>
        <h3>User Provided Content; Feedback</h3>
        <p>The ComplianceReward service may provide you with an opportunity to submit text or ideas, including question submissions, cover letters, resumes, feedback about the ComplianceReward service, customer service interactions, and any other text, images, ideas or other content and material that you provide ("User Feedback"). You hereby grant us a nonexclusive, worldwide, perpetual, irrevocable, unlimited, fully paid up, royalty-free, transferable, assignable and sublicensable right and license to use and exploit the User Feedback in any manner, in any medium now or hereafter discovered, and for any and all commercial or non-commercial purposes, including modifying and preparing derivative works thereof which IMV shall exclusively own. Except as otherwise provided herein or as prohibited by applicable law, IMV may use the User Feedback without any duty to provide notice to, obtain the consent of, account to or otherwise be subject to any obligation or duty to you. You irrevocably and forever release and discharge IMV and its employees and agents from any and all claims relating to our use of the User Feedback, including any and all attribution or other rights known as "moral rights".</p>
        <h3>Amendments</h3>
        <p>IMV may update these Terms at its discretion and from time to time. It is your responsibility to review these Terms fully and to continue using the ComplianceReward service only if you agree to these Terms. IMV may notify you of minor updates to these Terms via email or web notification, and for more significant changes, we may require you to accept such change by a click or other action before you are permitted to continue using the ComplianceReward service (for example, via a pop-up screen or popover message). Your continued use of the ComplianceReward service constitutes your consent to all amendments made to these Terms, and you must consent to all updates in order to continue using the ComplianceReward service.</p>
        <p>Platform <b>Independent;</b> Custom Terms</p>
        <p>These Terms apply to your use of the ComplianceReward service, regardless of the platform through which you obtained access to it . However, the platform may require you to agree to additional terms between you and the platform provider. We are not responsible for any third party terms. To the extent applicable and permissible, these Terms constitute a "custom end user license agreement" and replace and supersede any form agreement that a platform may provide.</p>
        <p>The ComplianceReward service and related documentation are "Commercial Items", as that term is defined at 48 C.F.R. §2.101, consisting of "Commercial Computer Software" and "Commercial Computer Software Documentation", as such terms are used in 48 C.F.R. §12.212 or 48 C.F.R. §227.7202, as applicable. Consistent with 48 C.F.R. §12.212 or 48 C.F.R. §227.7202-1 through 227.7202-4, as applicable, the Commercial Computer Software and Commercial Computer Software Documentation are being licensed to any U.S. Government end users (a) only as Commercial Items and (b) with only those rights as are granted to all other end users pursuant to these Terms.</p>
        <h3>Dispute Resolution</h3>
        <p>PLEASE READ THE FOLLOWING PARAGRAPHS CAREFULLY BECAUSE THEY REQUIRE YOU TO ARBITRATE DISPUTES WITH IMV AND LIMIT THE MANNER IN WHICH YOU CAN SEEK RELIEF FROM US.</p>
        <p>Applicability of Arbitration Agreement</p>
        <p>All claims and disputes between the parties that cannot be resolved informally must be resolved by binding arbitration on an individual basis under the terms set forth below (the "Arbitration Agreement"). Notwithstanding the foregoing, in the event of any actual, alleged or threatened violation of confidentiality or violation of the other party’s intellectual property or other proprietary rights, the non-breaching party may immediately resort to court proceedings in a court of competent jurisdiction as set forth below in order to seek immediate equitable relief without posting of a bond, proof of damages or other similar requirement.</p>
        <p>This Arbitration Agreement applies to you and IMV, and to any subsidiaries, affiliates, agents, employees, predecessors in interest, successors, and assigns, as well as all authorized or unauthorized users or beneficiaries of Service provided under the Terms.</p>
        <p>The arbitration proceeding will be administered by JAMS pursuant to its Streamlined Arbitration Rules and Procedures before an arbitrator selected by and pursuant to the rules of JAMS. Any final award may be filed and enforced in any court of competent jurisdiction. The parties shall share equally in the costs assessed for the arbitration. Any such arbitration will take place at a location within the United States federal judicial district identified below and will apply the substantive law set forth below. Any arbitration proceeding may not be consolidated or joined with any other proceeding and will not proceed as a class action. THE PARTIES UNDERSTAND THAT THEY WOULD HAVE HAD A RIGHT OR OPPORTUNITY TO LITIGATE DISPUTES THROUGH A COURT, TO HAVE A JUDGE OR JURY DECIDE THEIR CASE, AND TO PARTICIPATE IN A CLASS ACTION OR OTHER PROCEEDING INVOLVING MULTIPLE CLAIMANTS, BUT THEY CHOOSE TO HAVE ANY DISPUTES DECIDED THROUGH INDIVIDUAL ARBITRATION.</p>
        <p>The decision of the arbitrator will be a final and binding resolution of the dispute. This Arbitration Agreement is made pursuant to a transaction involving interstate commerce and will be governed by the Federal Arbitration Act, 9 U.S.C. Sections 1–16. Judgment upon the award may be entered in any court having jurisdiction.</p>
        <p><b>Survival</b> This provision will survive the termination of your relationship with IMV.</p>
        <p><b>Time Limitation on Claims</b> You agree that any claim you may have arising out of or related to your relationship with IMV must be filed within one year after such claim arose; otherwise, your claim is permanently barred.</p>
        <h3>Governing Law</h3>
        <p>The laws of the State of <span class="bottom-solid-line">________________</span> (other than rules that would apply the law of other states) govern these Terms and your use of the ComplianceReward service. Your use of the ComplianceReward service may also be subject to other local, state, national, or international laws. The exclusive jurisdiction and venue for any actions that you bring against IMV relating to your use of the ComplianceReward services shall be the courts located in or having jurisdiction over <span class="bottom-solid-line">_________________</span> County in the State of <span class="bottom-solid-line">___________________</span>. YOU AGREE TO WAIVE YOUR RIGHT TO A JURY TRIAL. UNLESS PROHIBITED BY YOUR JURISDICTION, YOU HEREBY WAIVE ANY RIGHT YOU MAY HAVE TO JOIN OR CONSOLIDATE YOUR CLAIMS AGAINST IMV WITH THE CLAIMS OF THIRD PARTIES.</p>
        <h3>Severability</h3>
        <p>If any provision of these Terms shall be deemed unlawful, void or for any reason unenforceable, then that provision shall be deemed severable from these Terms and shall not affect the validity and enforceability of any remaining provisions.</p>
        <h3>Entire Agreement</h3>
        <p>These Terms supersede all prior understandings regarding the Services and represent the complete agreement between you and IMV. These Terms do not create or confer any third-party beneficiary rights. We may, at our sole discretion, change or modify these Terms at any time. If we make changes to these Terms, we will provide notice of such changes, such as by sending a notification, posting a notice on the Service, or updating the "Last Updated" date above. Your continued use of the Service will confirm your acceptance of the updated Terms. We encourage you to frequently review the Terms to ensure you understand the terms and conditions that apply to your use of the Service. If you do not agree to the revised Terms, you must stop using the Service and delete your IMV account.</p>
        <h3>Contacting Us</h3>
        <p>If you have any other questions or concerns regarding these Terms of Service, please contact us as follows: via email at: <a href="mailto:info@ComplianceReward.com">info@ComplianceReward.com</a> or by Mail at:</p>
        <div class="trow_" style="padding-left: 7vw;">
            <p>Ingenious Mobility Ventures, LLC </p>
            <p>9001 Airport Freeway,</p>
            <p>North Richland Hills, TX 76180 </p>
            <p><a href="www.ComplianceReward.com">www.ComplianceReward.com</a>.</p>
        </div>
    </div>

</div>
</div>
</div>    		</div>
    </div>
</section>
@endsection