@extends('layouts.compliance')
@section('content')
<div class="row pt-40_" style="display: flex; min-height: 100%;">
  <div class="col-sm-12" style="display: flex; flex-wrap: wrap;">
  	<div class="row">  		<div class="col-sm-6">
  			<div class="trow_ mb-14_">  				<div class="fs-17_ weight_600">Welcome Laura</div>  			</div>
  			<div class="trow_ mb-24_">  				<p class="ma-0_ fs-16_" style="line-height: 1.7em;">You are securely connected to Compliance Reward&#8480;, where you enroll your                   most valuable patients to receive convenient and informative messages                   and activities to support their treatments!</p>  			</div>  			  			<div class="trow_ mb-14_">  				<div class="fs-17_ txt-blue weight_600">Patient Search</div>  			</div>  			  			<div class="trow_">  				<form class="" style="width: 70%; min-width: 270px;">					<div class="input-group c-dib_" style="padding: 7px;border-radius: 6px;background-color: #fff;border: solid 1px #afbcc2;">						<input type="text" class="form-control fs-16_" name="query" id="query" style="line-height: 1.2em !important;height: 36px;border: 0px;padding-left: 0px;padding-left: 6px;" placeholder="Search using name, email, phone etc" data-provide="typeahead" autocomplete="off">
						<div class="input-group-append" style="background-color: #fff;color: #fff !important;margin: 0px;border-radius: 0px 13px 13px 0px;">							<button type="submit" class="btn bg-blue-txt-wht" style="border-radius: 6px;width: 40px;text-align: center;height: 36px;padding: 0px;">								<i class="fa fa-search fs-20_ " style="line-height: 24px;"></i>							</button>						</div>					</div>				</form>  			</div>  			  		</div>  		
  		<div class="col-sm-6">  			<div class="trow_ mb-14_">  				<div class="fs-17_ txt-blue weight_600">BEST MATCH(ES)</div>  			</div>  			  			<div class="row">
  				<div class="col-sm-12 table-responsive">    				<table class="table bordered-hd-blue-shade">    					<thead class="bg-blue">    						<tr class="weight_500-force-childs">    							<th class="txt-wht">First Name</th>    							<th class="txt-wht">Last Name</th>    							<th class="txt-wht">Gender</th>    							<th class="txt-wht">DOB</th>    							<th class="txt-wht">Mobile</th>    							<th class="txt-wht">Zip</th>    						</tr>    					</thead>    					<tbody>
    						<tr>    							<td>Rob</td>    							<td>Jonesma</td>    							<td>(M)</td>    							<td>10/19/85</td>    							<td>(720) 866-5502</td>    							<td>26740</td>    						</tr>    						<tr>    							<td>Robert</td>    							<td>Jonestra</td>    							<td>(M)</td>    							<td>12/12/2000</td>    							<td>(405) 210-2715</td>    							<td>98578</td>    						</tr>
    						<tr>    							<td>Roberta</td>    							<td>Jones</td>    							<td>(F)</td>    							<td>12/12/2000</td>    							<td>(720) 866-5502</td>    							<td>26740</td>    						</tr>    					</tbody>    				</table>    			</div>  			</div>  			  			<div class="row">  				<div class="col-sm-12">                    <div class="elm-left">    					<button class="btn bg-blue-txt-wht weight_600 fs-14_" style="line-height: 30px; padding: .1rem .75rem;">+ Add New</button>    				</div>            </div>  			</div>  			  			  		</div> 		
  	</div>  	  	<div class="row images-hidden-at-load" style="min-width: 100%; display: flex; align-items: center;">        <div class="col-sm-6">            <div class="float-left">                <img src="images/well.png" class="img-fluid">            </div>        </div>        <div class="col-sm-6">            <div class="float-right">                <img src="images/total.png" class="img-fluid">            </div>        </div>    </div>
  	
  </div>
</div>
@endsection